export enum ActionTypes {
  MOVE_CELL = "move_cell",
  DELETE_CELL = "delete_cell",
  UPDATE_CELL = "update_cell",
  INSERT_CELL_AFTER = "insert_cell_after",
  BUNDLE_START = "bundle_start",
  BUNDLE_COMPLETE = "bundle_complete",
  FETCH_CELLS = "fetch_cells",
  FETCH_CELLS_COMPLETE = "fetch_cells_complete",
  FETCH_CELLS_ERROR = "fetch_cells_error",
  SAVE_CELLS_START = "save_cells_start",
  SAVE_CELLS_COMPLETE = "save_cells_complete",
  SAVE_CELLS_ERROR = "save_cells_error",
  LOGIN_START = "login_start",
  LOGIN_SUCCESS = "login_success",
  LOGIN_ERROR = "login_error",
  LOGOUT_START = "logout_start",
  LOGOUT_SUCCESS = "logout_success",
  SIGNUP_START = "signup_start",
  SIGNUP_ERROR = "signup_error",
  SIGNUP_SUCCESS = "signup_success",
}
